ALTER TABLE certificates ADD COLUMN source TEXT NOT NULL DEFAULT 'upload';
ALTER TABLE certificates ADD COLUMN expires_at INTEGER NOT NULL DEFAULT 0;
ALTER TABLE certificates ADD COLUMN acme_email TEXT NOT NULL DEFAULT '';
ALTER TABLE certificates ADD COLUMN last_error TEXT NOT NULL DEFAULT '';
ALTER TABLE certificates ADD COLUMN auto_renew INTEGER NOT NULL DEFAULT 0;
